version: 2.1

orbs:
  jq: circleci/jq@3.0.0

jobs:
  prepare-environment:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - jq/install:
          version: jq-1.7
  run-tests:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: execute tests
          command: ./src/tests/crud.sh
  

workflows:
  test-and-build:
    jobs:
      - prepare-environment
      - run-tests:
          requires:
            - prepare-environment
      
