version: 2.1

default-docker-image: &default-docker-image
  docker:
    - image: cimg/base:2023.03

orbs:
  jq: circleci/jq@3.0.0
  docker: circleci/docker@2.4.0

jobs:
  prepare-environment:
    <<: *default-docker-image
    steps:
      - jq/install:
          version: jq-1.7
  run-tests:
    <<: *default-docker-image
    steps:
      - checkout
      - run:
          name: execute test
          command: bash ./src/tests/crud.sh

workflows:
  test-and-build:
    jobs:
      - prepare-environment
      - run-tests:
          requires:
            - prepare-environment
      - docker/publish:
          context: DOCKER_CREDENTIALS
          image: viniciussousaazevedo/hacktoberfest_ci_sample
          requires:
            - run-tests
          filters:
            branches:
              only:
                - main
      
