version: 2.1

# YAML anchors
default-docker-image: &default-docker-image
  docker:
    - image: cimg/base:2023.03 # Definir uma imagem Docker específica para um job no CircleCI garante que o ambiente seja consistente e previsível, independentemente de onde o pipeline esteja sendo executado. As vezes, certas imagens já tem conteúdos prontos que facilitam o desenrolar de um job.

orbs:
  jq: circleci/jq@3.0.0
  docker: circleci/docker@2.4.0
  # WARNING: cuidado com orbes ;)

jobs:
  prepare-environment:
    <<: *default-docker-image
    steps:
      - jq/install:
          version: jq-1.7
      # Qualquer etapa de build (ex: mvn clean package) entraria aqui também
  run-tests:
    <<: *default-docker-image
    steps:
      - checkout # recuperar o código-fonte do repositório versionado
      - run:
          name: execute tests
          command: bash ./src/tests/crud.sh      

workflows:
  test-and-build:
    jobs:
      - prepare-environment
      - run-tests:
          requires:
            - prepare-environment
      - docker/publish:
          context: DOCKER_CREDENTIALS # Foi usado env vars com valores default
          image: viniciussousaazevedo/hacktoberfest_ci_sample
          requires:
            - run-tests
          filters:
            branches:
              only:
                - main
      
